# Generated by Django 5.2.1 on 2025-06-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
