# Generated by Django 5.2.1 on 2025-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointment_problem_description_doctor_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
