# Generated by Django 5.2.1 on 2025-05-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor_x_doctor_facebook_doctor_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_experience',
            field=models.BooleanField(default=False, verbose_name='Has Experience'),
        ),
    ]
