# Generated by Django 5.2.1 on 2025-06-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
